//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemandTrackerv1._1
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdersInfo
    {
        public int Id { get; set; }
        public string header { get; set; }
        public string dropdownmenu { get; set; }
    }
}
