//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemandTrackerv1._1
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestViewUser
    {
        public string Creator { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string Status { get; set; }
    }
}
